---
title: "Spin-off"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidyboot)
library(jsonlite)
library(coda)
library(ggthemes)
library(RColorBrewer)
library(ggpubr)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}


hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}


```

# Data

## data prep for model

```{r}
data <- read_csv("../data/data.csv")
```
# descriptives
```{r}
data %>%
  group_by(subage)%>%
  filter(test_day == 2)%>%
  summarise(complete_retest_data = length(unique(id)))
```

```{r}
data %>%
  filter(task == "mutual_exclusivity")%>%
  group_by(subage, item)%>%
  summarise(mean = mean(correct))

data %>%
  filter(task == "simple_inf")%>%
  group_by(item)%>%
  summarise(mean = mean(correct))

data %>%
  filter(task == "ad_hoc_implicature")%>%
  group_by(item)%>%
  summarise(mean = mean(correct))
```


```{r}
# exporting data to JSON
data %>%
  filter(task != "card_sorting",
         task != "discourse_continuity")%>%
  write_json("../data/data.json")
```

# Model 

## model output
```{r}
model_samples <- bind_rows(
  fread("../model/output/model_total-chain1.csv")%>%mutate(chain = 1),
  fread("../model/output/model_total-chain2.csv")%>%mutate(chain = 2),
  fread("../model/output/model_total-chain3.csv")%>%mutate(chain = 3),
  fread("../model/output/model_total-chain4.csv")%>%mutate(chain = 4),
  fread("../model/output/model_total-chain5.csv")%>%mutate(chain = 5),
  fread("../model/output/model_total-chain6.csv")%>%mutate(chain = 6)
  )

model_raw <- model_samples%>%
  select(-f)%>%
  rename(paramter = a,
         type = b,
         task = c,
         id = d,
         value = e
         )%>%
  mutate(chain = factor(chain))

model <- model_raw
  
saveRDS(model, "../model/output/model.rds")

model <- readRDS("../model/output/model.rds")
```

## Visualize paramters

### Semantic Knowledge

#### Global semantic knowledge

```{r}
global_sem <- model %>%
  filter(paramter == "semantic_knowledge",
         type == "global_parameter")

ggplot(global_sem, aes(x = value, col = chain, fill=chain))+
  geom_density(alpha = 0.3)+
  ggtitle("Global Semantic Knowledge")+
  xlab("Value")+
  theme_minimal()+
  facet_grid(~task)+
  scale_color_ptol()+
  scale_fill_ptol()+
  guides()

```

#### Item specific semantic knowledge

```{r}

item_params <- model %>%
  filter(type == "item_parameter")

item_summary <- item_params %>%
  group_by(chain, id, task)%>%
  summarise(mode = estimate_mode(value),
            uci = hdi_upper(value),
            lci = hdi_lower(value))

sem_know_map <- item_summary%>%
  select(-uci,-lci)%>%
  spread(task, -chain) %>%
  expand_grid(., age = unique(data$c_age)) %>%
  mutate(sem_know = plogis(intercept + slope * age))

ggarrange(
  
ggplot(item_params, aes(x = value, col = id, fill=id, group = chain))+
  geom_density(alpha = 0.3, aes(lty = chain))+
  xlab("")+
  theme_minimal()+
  scale_color_viridis_d()+
  scale_fill_viridis_d()+
  guides(col = F, fill = F, lty = F)+
  facet_grid(id ~task)
,

ggplot(data = sem_know_map, aes(x = age+3, y= sem_know, col = id))+
  geom_line( aes(lty = chain),size = 1)+
  ylab("Semantic knowledge")+
  xlab("Age")+
  ylim(0,1)+
  theme_minimal()+
  scale_colour_viridis_d(name = "Object")

)
```

### Speaker Optimality

#### Global speaker optimality

```{r}
global_so <- model %>%
  filter(paramter == "speaker_optimality",
         type == "global_parameter",
         task != "scale_parameter")%>%
  mutate(task = factor(task, levels = c("intercept", "slope","sigma")))

ggplot(global_so, aes(x = value, col = chain, fill=chain))+
  geom_density(alpha = 0.3)+
  xlab("Value")+
  ggtitle("Global speaker optimality")+
  theme_minimal()+
  facet_grid(~task)+
  scale_color_ptol()+
  scale_fill_ptol()+
  guides()
```


#### Subject specific speaker optimality
```{r}
so_id <- model %>%
  filter(paramter == "speaker_optimality",
         type == "subj_parameter",
         task == "speaker_optimality")

ggplot(so_id, aes(x = value, col = chain, fill=chain))+
  geom_density(alpha = 0.3)+
  xlab("Value")+
  ggtitle("ID specific speaker optimality")+
  theme_minimal()+
  facet_wrap(~id)+
  scale_color_ptol()+
  scale_fill_ptol()+
  guides()
```

```{r}
so_id_summary <- so_id %>%
  group_by(chain,task, id)%>%
  summarise(mode = mean(value),
            uci = hdi_upper(value),
            lci = hdi_lower(value))


ggplot(so_id_summary, aes(x = id, y = mode, col = chain))+
  geom_pointrange(aes(ymin = lci, ymax = uci, pch = chain), position = position_dodge(width = .5))+
  ggtitle("ID specific speaker optimality")+
  ylab("Speaker Optimality Parameter")+
  theme_minimal()+
  scale_color_ptol()+
  scale_fill_ptol()+
  guides(lty = F)
  #ylim(0,5)

```
#### Scale parameter

```{r}
scale <- model %>%
  filter(paramter == "speaker_optimality",
         task == "scale_parameter")

ggplot(scale, aes(x = value, col = chain, fill=chain))+
  geom_density(alpha = 0.3)+
  xlab("Scale Parameter")+
  facet_grid(~id)+
  theme_minimal()+
  scale_color_ptol()+
  scale_fill_ptol()+
  guides()

```

# Correlation of Speaker Optimality Parameter with other measures

```{r}
cor_data <- so_id %>%
  group_by(id)%>%
  summarise(mode = mean(value),
            uci = hdi_upper(value),
            lci = hdi_lower(value))%>%
  right_join(
    data %>%
      group_by(id,task)%>%
      summarise(mean= mean(correct))%>%
      filter(task != "ad_hoc_implicature",
             task != "mutual_exclusivity",
             task != "simple_inf")
  )


ggplot(cor_data, aes(x = mean, y = mode))+
  geom_point(size = 2, pch = 4)+
  labs(x = "Measure", y = "Speaker optimality")+
  facet_grid(~task)+
  geom_smooth(method = "lm", col = "black")+
  stat_cor(method = "pearson", aes(x = mean, y = mode), inherit.aes = F, size = 3)+
  theme_few()+
  coord_fixed(ratio = 1/7)+
  ylim(0,7)
````